name: Microservices CI pipeline v0.0.1

on:
    push:
        branches:
            - 'feature/**'            
            - '!feature/technical-settings'
            - main

jobs:
    #it setting  variable about which branch was changed   and which run shoule be run
    changes-detection:
        runs-on: ubuntu-latest
        outputs: 
            flag_notification_center: ${{ steps.filter_for_dorny.outputs.notification_center_check_result }}
            flag_sms_service: ${{ steps.filter_for_dorny.outputs.sms_service_check_result }}
            flag_watertankpower_service: ${{ steps.filter_for_dorny.outputs.watertankpower_service_check_result }}
        steps:
            - uses: actions/checkout@v4
            #it track changes in commit
            - uses: dorny/paths-filter@v3   
              id: filter_for_dorny
              with: 
                filters: |
                    notification_center_check_result:
                        - 'ServiceNotificationCenter/**'
                    sms_service_check_result:
                        - 'ServiceSMS/**'
                    watertankpower_service_check_result:
                        - 'ServiceTurnOnWaterTank/**'
    
    #proper test cases
    test-water-tank-power-service:      
        needs: changes-detection
        if: ${{ needs.changes-detection.outputs.flag_watertankpower_service == 'true' }}
        runs-on: ubuntu-latest
        env:
          SERVICE_DIR: 'ServiceTurnOnWaterTank'
        steps:
            - name: Repo checkout 
              uses: actions/checkout@v4
              
            - name: py init
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
                cache-dependency-path: '${{env.SERVICE_DIR}}/requirements.txt'

            - name: py packages
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r $SERVICE_DIR/requirements.txt --user || true
            
            - name: Run pytest ServiceNotificationCenter
              env:
                PYTHONPATH: ${{ github.workspace }}
              run: |
                 python -m pytest $SERVICE_DIR/


    test-notification-center:
        needs: changes-detection
        if: ${{ needs.changes-detection.outputs.flag_notification_center == 'true'}}
        runs-on: ubuntu-latest
        env:
          SERVICE_DIR: 'ServiceNotificationCenter'
        steps:
            - name: Repo checkout 
              uses: actions/checkout@v4
              
            - name: py init
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
                cache-dependency-path: '${{env.SERVICE_DIR}}/requirements.txt'
            
            - name: py packages
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r $SERVICE_DIR/requirements.txt --user || true
            
            - name: Run pytest ServiceNotificationCenter
              env:
                PYTHONPATH: ${{ github.workspace }}
              run: |
                 python -m pytest $SERVICE_DIR/
    
    test-sms-service:
        needs: changes-detection
        if: ${{ needs.changes-detection.outputs.flag_sms_service == 'true'}} 
        runs-on: ubuntu-latest
        env:
          SERVICE_DIR: 'ServiceSMS'
        steps:
            - name: Repo checkout 
              uses: actions/checkout@v4
              
            - name: py init
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
                cache-dependency-path: '${{env.SERVICE_DIR}}/requirements.txt'
            
            - name: py packages
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r $ServiceSMS/requirements.txt --user || true

            - name: Run pytest ServiceSMS
              env:
                PYTHONPATH: ${{ github.workspace }}
              run: |
                 python -m pytest $ServiceSMS/
